const fs = require("fs")
const path = require("path")

const resolvePythonInterpreter = () => {
  const explicit = process.env.PYTHON_INTERPRETER
  if (explicit) {
    return explicit
  }

  const candidates = [
    path.join(__dirname, ".venv/bin/python"),
    path.join(__dirname, "backend/.venv/bin/python"),
  ]

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }

  return "python3"
}

const discordWorkerCount = Number(process.env.BOT_WORKER_COUNT || process.env.BOT_SHARD_COUNT || 4)

const discordWorkerEnv = {
  NODE_ENV: "production",
  PYTHONIOENCODING: "utf-8",
  PYTHONUNBUFFERED: "1",
  AI_INTRA_THREADS: "1",
  BACKEND_API_URL: "http://127.0.0.1:5001",
  KEYWORD_IMAGE_SEARCH_PROVIDER: "searchapi_google_maps",
  DISCORD_SIMILARITY_THRESHOLD: "0.63",
  DISCORD_IMAGE_REPLY_MIN_TOP1_MARGIN: "0.00",
  DISCORD_MESSAGE_STAGE_SLOW_SECONDS: "45.0",
  DISCORD_MESSAGE_KEYWORD_SEARCH_TIMEOUT_SECONDS: "240",
  KEYWORD_TEXT_SEARCH_TIMEOUT_SECONDS: "120",
  KEYWORD_TEXT_SEARCH_MAX_INFLIGHT: "2",
  DISCORD_MESSAGE_IMAGE_REPLY_TIMEOUT_SECONDS: "900",
  DISCORD_IMAGE_REPLY_MAX_ATTACHMENTS_PER_MESSAGE: "8",
  DISCORD_SEND_MAX_INFLIGHT: "1",
  DISCORD_SEND_INTERVAL_SECONDS: "0.35",
  DISCORD_SEND_TYPING_ENABLED: "0",
  DISCORD_BOUND_CHANNEL_CACHE_TTL_SECONDS: "5",
  DISCORD_HEARTBEAT_TIMEOUT: "240.0",
  DISCORD_STARTUP_STAGGER_SECONDS: "5.0",
  DISCORD_IMAGE_RECOGNITION_REQUEST_TIMEOUT_SECONDS: "900.0",
  DISCORD_IMAGE_RECOGNITION_MAX_INFLIGHT: "4",
  DISCORD_IMAGE_RECOGNITION_MAX_ATTEMPTS: "3",
  DISCORD_IMAGE_RECOGNITION_RETRY_DELAY_SECONDS: "3.0",
  BOT_SHARD_COUNT: String(discordWorkerCount),
  BOT_WATCHDOG_INTERVAL_SECONDS: "60",
  BOT_WATCHDOG_RESTART_INTERVAL_SECONDS: "300",
  BOT_WATCHDOG_DISCONNECTED_GRACE_SECONDS: "180",
  BOT_WATCHDOG_RESTART_START_DELAY_SECONDS: "20",
  BOT_AUTOSTART_RECONCILE_SECONDS: "60",
  BOT_STATUS_REFRESH_SECONDS: "30",
  BOT_REVIEW_DISPATCH_POLL_SECONDS: "2",
  BOT_REVIEW_DISPATCH_BATCH_SIZE: "20",
  BOT_REVIEW_DISPATCH_STALE_SECONDS: "300"
}

const createDiscordWorker = (index) => ({
  name: `discord-worker-${index}`,
  script: "bot_worker.py",
  interpreter: resolvePythonInterpreter(),
  cwd: "./backend",
  kill_timeout: 10000,
  max_restarts: 20,
  min_uptime: "10s",
  env: {
    ...discordWorkerEnv,
    BOT_SHARD_INDEX: String(index)
  }
})

module.exports = {
  apps: [
    {
      name: "web-frontend",
      // 指向 next 的二进制执行文件
      script: "./node_modules/next/dist/bin/next",
      args: "start",
      cwd: "./frontend",
      // 默认就是 node 模式
      env: {
        NODE_ENV: "production",
        PORT: 3000
      }
    },
    {
      name: "python-api",
      // 脚本路径，相对于下面的 cwd
      script: "app.py",
      // 使用项目依赖完整的 Python 解释器，避免系统 python 缺 torch/transformers
      interpreter: resolvePythonInterpreter(),
      cwd: "./backend",
      // 必须确保 kill_timeout 足够，防止重启时旧进程没杀掉
      kill_timeout: 30000,
      max_memory_restart: "16G",
      env: {
        NODE_ENV: "production",
        PYTHONIOENCODING: "utf-8",
        PYTHONUNBUFFERED: "1",
        AI_INTRA_THREADS: "1",
        AI_STARTUP_WARMUP: "0",
        DISCORD_BOT_EMBEDDED_ENABLED: "0",
        BOT_DISABLE_EMBEDDED: "1",
        BOT_REVIEW_WORKER_DISPATCH: "1",
        BACKEND_API_URL: "http://127.0.0.1:5001",
        LIVE_IMAGE_SEARCH_STRATEGY: "siglip2_rerank",
        LIVE_IMAGE_SEARCH_STARTUP_WARM_STRATEGY: "0",
        LIVE_IMAGE_SEARCH_STREAMING_ENABLED: "1",
        LIVE_IMAGE_SEARCH_STREAMING_FORCE: "1",
        LIVE_IMAGE_SEARCH_SCOPED_CATALOG_ENABLED: "0",
        LIVE_IMAGE_SEARCH_MAX_INFLIGHT: "4",
        LIVE_IMAGE_SEARCH_QUEUE_MAX_SIZE: "0",
        LIVE_IMAGE_SEARCH_QUEUE_TIMEOUT_SECONDS: "0",
        LIVE_IMAGE_SEARCH_EXECUTION_TIMEOUT_SECONDS: "0",
        LIVE_IMAGE_SEARCH_QUERY_CONTEXT_CACHE_TTL_SECONDS: "120.0",
        LIVE_IMAGE_SEARCH_QUERY_CONTEXT_CACHE_MAX_ENTRIES: "64",
        LIVE_IMAGE_SEARCH_VECTOR_CONTEXT_CACHE_SCOPES: "64",
        LIVE_IMAGE_SEARCH_VECTOR_CONTEXT_SIGNATURE_TTL_SECONDS: "3600.0",
        LIVE_IMAGE_SEARCH_VECTOR_BATCH_SIZE: "4096",
        LIVE_IMAGE_SEARCH_SCOPED_CATALOG_CACHE_SCOPES: "4",
        LIVE_IMAGE_SEARCH_SCOPED_CATALOG_PREPARE_MAX_WORKERS: "1",
        LIVE_IMAGE_SEARCH_STARTUP_PREPARE_CATALOG: "0",
        LIVE_IMAGE_SEARCH_STARTUP_LOAD_SCOPED_CATALOGS: "1",
        LIVE_IMAGE_SEARCH_STARTUP_BUILD_SCOPED_CATALOGS: "0",
        LIVE_IMAGE_SEARCH_BACKGROUND_LOAD_SCOPED_CATALOGS: "0",
        RETRIEVAL_CACHE_AUTO_BACKFILL: "0",
        KEYWORD_IMAGE_SEARCH_PROVIDER: "searchapi_google_maps",
        KEYWORD_TEXT_SEARCH_API_MAX_INFLIGHT: "3",
        KEYWORD_TEXT_SEARCH_API_QUEUE_TIMEOUT_SECONDS: "0",
        DISCORD_SIMILARITY_THRESHOLD: "0.63",
        DISCORD_IMAGE_REPLY_MIN_TOP1_MARGIN: "0.00",
        DISCORD_MESSAGE_STAGE_SLOW_SECONDS: "45.0",
        SIGLIP2_RERANK_IMAGE_ONLY: "1",
        SIGLIP2_RERANK_IMAGE_WEIGHT: "1.00",
        SIGLIP2_RERANK_COLOR_WEIGHT: "0.00",
        SIGLIP2_RERANK_TEXT_WEIGHT: "0.00",
        SIGLIP2_RERANK_CATEGORY_WEIGHT: "0.00",
        SIGLIP2_RERANK_BONUS_SCORE: "0.00",
        SIGLIP2_RERANK_QUERY_FUSION: "0",
        SIGLIP2_RERANK_QUERY_MAX_SIDE: "336",
        SIGLIP2_RERANK_QUERY_RAW_WEIGHT: "1.00",
        SIGLIP2_RERANK_QUERY_CENTER_WEIGHT: "0.00",
        SIGLIP2_RERANK_QUERY_YOLO_WEIGHT: "0.00",
        SIGLIP2_RERANK_ADAPTIVE_RAW_CENTER: "0",
        SIGLIP2_RERANK_ADAPTIVE_RAW_DELTA: "0.05",
        SIGLIP2_RERANK_FAST_RANK_CACHE_SCOPES: "4",
        SIGLIP2_RERANK_FAST_RANK_CANDIDATE_K: "4096",
        LIVE_IMAGE_SEARCH_PRODUCT_SUPPORT_MODE: "auto",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_ENABLED: "0",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_WEIGHT: "1.0",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_LIMIT: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_ENABLED: "0",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_MAX_SOURCE_IMAGES: "3",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_MAX_RECORDS: "5",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_INCLUDE_ORIGINALS: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_CENTER_CROP: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_COMPRESSED: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_PERSPECTIVE: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_BACKGROUND: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_DIR: "data/live_image_support",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_ENABLED: "0",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_REFRESH_ON_UPLOAD: "0",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_DIR: "data/live_image_external_support",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_MAX_QUERIES: "4",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_SEARCH_LIMIT: "12",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_MAX_RECORDS: "4",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_PER_QUERY_LIMIT: "2",
        SIGLIP2_RERANK_STAGE2_CANDIDATE_K: "5",
        SIGLIP2_RERANK_STAGE2_RIDGE_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_RIDGE_ALPHA: "50",
        SIGLIP2_RERANK_STAGE2_RIDGE_BLEND: "0.05",
        SIGLIP2_RERANK_STAGE2_AUTO_REPORT_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_AUTO_REPORT_GLOB: "backend/benchmarks/results/live_http_shop_1774155549_*/live_http_*.json",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_REPORT_PATH: "",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_MIN_COUNT: "2",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_PAIR_LIMIT: "10",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_ALPHA: "10",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_BLEND: "0.02",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_REPORT_PATH: "",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_MIN_COUNT: "2",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_PAIR_LIMIT: "40",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_NEAR_MISS_K: "3",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_ALPHA: "50",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_SWAP_ENABLED: "1",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_PAIR_MARGIN: "0.01",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_QUERY_REPEAT: "2",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_CATALOG_REPEAT: "1",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_CATALOG_ONLY_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_DYNAMIC_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_QUERY_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_PAIR_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_SUPPORT_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_BLEND: "0.04",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_TOP2_WEIGHT: "0.25",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_MEAN_WEIGHT: "0.00",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_MIN_SUPPORT: "1",
        RETRIEVAL_PRODUCT_RANK_SECOND_BEST_WEIGHT: "0.00",
        RETRIEVAL_PRODUCT_RANK_TOP3_MEAN_WEIGHT: "0.12",
        RETRIEVAL_PRODUCT_RANK_TOP5_MEAN_WEIGHT: "0.08"
      }
    },
    ...Array.from({ length: discordWorkerCount }, (_, index) => createDiscordWorker(index))
  ]
}
