const fs = require("fs")
const path = require("path")

const resolvePythonInterpreter = () => {
  const explicit = process.env.PYTHON_INTERPRETER
  if (explicit) {
    return explicit
  }

  const candidates = [
    path.join(__dirname, ".venv/bin/python"),
    path.join(__dirname, "backend/.venv/bin/python"),
  ]

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }

  return "python3"
}

module.exports = {
  apps: [
    {
      name: "web-frontend",
      // 指向 next 的二进制执行文件
      script: "./node_modules/next/dist/bin/next",
      args: "start",
      cwd: "./frontend",
      // 默认就是 node 模式
      env: {
        NODE_ENV: "production",
        PORT: 3000
      }
    },
    {
      name: "python-api",
      // 脚本路径，相对于下面的 cwd
      script: "app.py",
      // 使用项目依赖完整的 Python 解释器，避免系统 python 缺 torch/transformers
      interpreter: resolvePythonInterpreter(),
      cwd: "./backend",
      // 必须确保 kill_timeout 足够，防止重启时旧进程没杀掉
      kill_timeout: 3000,
      env: {
        NODE_ENV: "production",
        PYTHONIOENCODING: "utf-8",
        PYTHONUNBUFFERED: "1",
        LIVE_IMAGE_SEARCH_STRATEGY: "siglip2_rerank",
        LIVE_IMAGE_SEARCH_STREAMING_ENABLED: "1",
        LIVE_IMAGE_SEARCH_STREAMING_FORCE: "1",
        LIVE_IMAGE_SEARCH_MAX_INFLIGHT: "1",
        LIVE_IMAGE_SEARCH_QUEUE_TIMEOUT_SECONDS: "2.0",
        LIVE_IMAGE_SEARCH_EXECUTION_TIMEOUT_SECONDS: "20.0",
        LIVE_IMAGE_SEARCH_STARTUP_PREPARE_CATALOG: "0",
        RETRIEVAL_CACHE_AUTO_BACKFILL: "0",
        DISCORD_SIMILARITY_THRESHOLD: "0.63",
        SIGLIP2_RERANK_IMAGE_WEIGHT: "1.00",
        SIGLIP2_RERANK_COLOR_WEIGHT: "0.00",
        SIGLIP2_RERANK_TEXT_WEIGHT: "0.00",
        SIGLIP2_RERANK_BONUS_SCORE: "0.00",
        SIGLIP2_RERANK_QUERY_FUSION: "1",
        SIGLIP2_RERANK_QUERY_RAW_WEIGHT: "0.00",
        SIGLIP2_RERANK_QUERY_CENTER_WEIGHT: "1.00",
        SIGLIP2_RERANK_QUERY_YOLO_WEIGHT: "0.00",
        SIGLIP2_RERANK_ADAPTIVE_RAW_CENTER: "0",
        SIGLIP2_RERANK_ADAPTIVE_RAW_DELTA: "0.05",
        LIVE_IMAGE_SEARCH_PRODUCT_SUPPORT_MODE: "auto",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_ENABLED: "0",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_WEIGHT: "1.0",
        SIGLIP2_RERANK_PRODUCT_SUPPORT_LIMIT: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_ENABLED: "0",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_MAX_SOURCE_IMAGES: "3",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_MAX_RECORDS: "5",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_INCLUDE_ORIGINALS: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_CENTER_CROP: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_COMPRESSED: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_PERSPECTIVE: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_BACKGROUND: "1",
        LIVE_IMAGE_SEARCH_AUTO_PRODUCT_SUPPORT_DIR: "data/live_image_support",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_ENABLED: "0",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_REFRESH_ON_UPLOAD: "0",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_DIR: "data/live_image_external_support",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_MAX_QUERIES: "4",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_SEARCH_LIMIT: "12",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_MAX_RECORDS: "4",
        LIVE_IMAGE_SEARCH_EXTERNAL_PRODUCT_SUPPORT_PER_QUERY_LIMIT: "2",
        SIGLIP2_RERANK_STAGE2_CANDIDATE_K: "5",
        SIGLIP2_RERANK_STAGE2_RIDGE_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_RIDGE_ALPHA: "50",
        SIGLIP2_RERANK_STAGE2_RIDGE_BLEND: "0.05",
        SIGLIP2_RERANK_STAGE2_AUTO_REPORT_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_AUTO_REPORT_GLOB: "backend/benchmarks/results/live_http_shop_1774155549_*/live_http_*.json",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_REPORT_PATH: "",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_MIN_COUNT: "2",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_PAIR_LIMIT: "10",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_ALPHA: "10",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_BLEND: "0.02",
        SIGLIP2_RERANK_STAGE2_HARD_NEGATIVE_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_REPORT_PATH: "",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_MIN_COUNT: "2",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_PAIR_LIMIT: "40",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_NEAR_MISS_K: "3",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_ALPHA: "50",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_SWAP_ENABLED: "1",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_PAIR_MARGIN: "0.01",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_QUERY_REPEAT: "2",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_CATALOG_REPEAT: "1",
        SIGLIP2_RERANK_STAGE2_QUERY_PAIR_CATALOG_ONLY_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_DYNAMIC_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_QUERY_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_CLUSTER_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_PAIR_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_TARGETED_SUPPORT_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_ENABLED: "0",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_BLEND: "0.04",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_SCORE_GAP: "0.05",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_TOP2_WEIGHT: "0.25",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_MEAN_WEIGHT: "0.00",
        SIGLIP2_RERANK_STAGE2_SUPPORT_STATS_MIN_SUPPORT: "1",
        RETRIEVAL_PRODUCT_RANK_SECOND_BEST_WEIGHT: "0.00",
        RETRIEVAL_PRODUCT_RANK_TOP3_MEAN_WEIGHT: "0.12",
        RETRIEVAL_PRODUCT_RANK_TOP5_MEAN_WEIGHT: "0.08"
      }
    }
  ]
}
